package compiler

import (
	"comp/ast"
	"comp/code"
	"comp/object"
	"fmt"
)

type EmittedInstruction struct {
	OpCode   code.Opcode
	Position int
}

type CompilationScope struct {
	instructions    code.Instructions
	lastInstruction EmittedInstruction
	prevInstruction EmittedInstruction
}

// Compiler transforms an Abstract Syntax Tree (AST) into bytecode instructions
// that can be executed by a virtual machine. It maintains a compilation state
// including generated bytecode, constants pool, and symbol table for variable
// resolution.
//
// The compilation process walks the AST recursively, emitting bytecode instructions
// for each node. Instructions are stored sequentially in memory, while constants
// (integers, strings, etc.) are stored in a separate pool and referenced by index.
type Compiler struct {
	constants   []object.Object
	symbolTable *SymbolTable
	scopes      []CompilationScope
	scopeIndex  int
}

// NewWithState creates a new Compiler instance initialized with the existing state.
// This is useful for resuming compilation or reusing the compiler state across
// multiple compilation passes.
//
// Returns a pointer to a newly created Compiler with the provided state injected.
func NewWithState(sym *SymbolTable, consts []object.Object) *Compiler {
	compiler := NewCompiler()
	compiler.symbolTable = sym
	compiler.constants = consts
	return compiler
}

// NewCompiler creates and returns a new Compiler instance with an empty / default state.
// This is the standard entry point for starting a new compilation process from scratch.
//
// Returns a pointer to the newly created Compiler instance.
func NewCompiler() *Compiler {
	mainScope := CompilationScope{instructions: code.Instructions{},
		lastInstruction: EmittedInstruction{},
		prevInstruction: EmittedInstruction{},
	}
	return &Compiler{
		constants:   []object.Object{},
		symbolTable: NewSymbolTable(),
		scopes:      []CompilationScope{mainScope},
		scopeIndex:  0,
	}
}

// TODO: improve error handling everywhere in the codebase.

// Compile walks the AST recursively until it encounters a node that can be compiled/evaluated.
//
// Works similar to the Evaluate function
func (c *Compiler) Compile(node ast.Node) error {
	switch node := node.(type) {
	case *ast.RootStatement:
		for _, stmt := range node.Statements {
			if err := c.Compile(stmt); err != nil {
				return err
			}
		}
	case *ast.LetStatement:
		if err := c.Compile(node.Value); err != nil {
			return err
		}
		symbol := c.symbolTable.Define(node.Name.Value)
		if symbol.Scope == GlobalScope {
			c.emit(code.OpSetGlobal, symbol.Index)
		} else {
			c.emit(code.OpSetLocal, symbol.Index)
		}
	case *ast.Identifier:
		symbol, ok := c.symbolTable.Resolve(node.Value)
		if !ok {
			return fmt.Errorf("undefined variable: %s", node.Value)
		}
		if symbol.Scope == GlobalScope {
			c.emit(code.OpGetGlobal, symbol.Index)
		} else {
			c.emit(code.OpGetLocal, symbol.Index)
		}
	case *ast.ExpressionStatement:
		if err := c.Compile(node.Expression); err != nil {
			return err
		}
		c.emit(code.OpPop)
	case *ast.BlockStatement:
		for _, stmt := range node.Statements {
			if err := c.Compile(stmt); err != nil {
				return err
			}
		}
	case *ast.FunctionLiteral:
		c.enterScope()
		if err := c.Compile(node.Body); err != nil {
			return err
		}
		if c.lastInstructionIs(code.OpPop) {
			c.replaceLastPopWithReturn()
		}
		if !c.lastInstructionIs(code.OpReturnValue) {
			c.emit(code.OpReturn)
		}
		var (
			instructions = c.leaveScope()
			compiledFunc = &object.CompiledFunction{Instructions: instructions}
		)
		c.emit(code.OpConstant, c.addConstant(compiledFunc))
	case *ast.ReturnStatement:
		if err := c.Compile(node.ReturnValue); err != nil {
			return err
		}
		c.emit(code.OpReturnValue)
	case *ast.CallExpression:
		if err := c.Compile(node.Function); err != nil {
			return err
		}
		c.emit(code.OpCall)
	case *ast.PrefixExpression:
		if err := c.Compile(node.Right); err != nil {
			return err
		}
		switch node.Operator {
		case "-":
			c.emit(code.OpMinus)
		case "!":
			c.emit(code.OpBang)
		default:
			return fmt.Errorf("invalid operation: %s", node.Operator)
		}
	case *ast.InfixExpression:
		if err := c.compileInfix(node); err != nil {
			return err
		}
	case *ast.IfExpression:
		if err := c.Compile(node.Condition); err != nil {
			return err
		}
		posJumpNotTruthy := c.emit(code.OpJumpNotTruthy, 1000)

		if err := c.Compile(node.Consequence); err != nil {
			return err
		}
		if c.lastInstructionIs(code.OpPop) {
			c.removeLastPop()
		}
		return c.handleJump(node, posJumpNotTruthy)
	case *ast.Boolean:
		if !node.Value {
			c.emit(code.OpFalse)
		} else {
			c.emit(code.OpTrue)
		}
	case *ast.IntegerLiteral:
		integer := &object.Integer{Value: node.Value}
		c.emit(code.OpConstant, c.addConstant(integer))

	case *ast.StringLiteral:
		str := &object.String{Value: node.Value}
		c.emit(code.OpConstant, c.addConstant(str))

	case *ast.HashLiteral:
		if err := c.compileHashLiteral(node); err != nil {
			return err
		}
	case *ast.ArrayLiteral:
		for _, elem := range node.Elements {
			if err := c.Compile(elem); err != nil {
				return err
			}
		}
		c.emit(code.OpArray, len(node.Elements))
	case *ast.IndexExpression:
		if err := c.Compile(node.Left); err != nil {
			return err
		}
		if err := c.Compile(node.Index); err != nil {
			return err
		}
		c.emit(code.OpIndex)
	}
	return nil
}

// enterScope creates a new empty compilation scope and makes it the current scope.
// This is used when entering nested contexts like function bodies.
func (c *Compiler) enterScope() {
	scope := CompilationScope{instructions: code.Instructions{},
		lastInstruction: EmittedInstruction{},
		prevInstruction: EmittedInstruction{},
	}
	c.scopes = append(c.scopes, scope)
	c.scopeIndex++
	c.symbolTable = NewEnclosedSymbolTable(c.symbolTable)
}

// leaveScope exits the current compilation scope and returns its generated instructions.
// The scope is removed from the stack and the previous scope becomes current.
func (c *Compiler) leaveScope() code.Instructions {
	instructions := c.currentInstructions()
	c.scopes = c.scopes[:len(c.scopes)-1]
	c.scopeIndex--
	c.symbolTable = c.symbolTable.Outer
	return instructions
}

func (c *Compiler) compileHashLiteral(node *ast.HashLiteral) error {
	keys := make([]ast.Expression, 0, len(node.Pairs))

	for key := range node.Pairs {
		keys = append(keys, key)
	}
	// ordering necessary for testing
	// slices.SortFunc(keys, func(a, b ast.Expression) int {
	// 	return strings.Compare(a.String(), b.String())
	// })
	for _, key := range keys {
		err := c.Compile(key)
		if err != nil {
			return err
		}
		err = c.Compile(node.Pairs[key])
		if err != nil {
			return err
		}
	}
	c.emit(code.OpHash, len(node.Pairs)*2)
	return nil
}

// currentInstructions returns the code.Instructions at the current scopeIndex
// in the scopes field of the Compiler.
func (c *Compiler) currentInstructions() code.Instructions {
	return c.scopes[c.scopeIndex].instructions
}

// changeOperand creates the instruction for the given operand and swaps the old
// instruction for the new one - including the operand.
func (c *Compiler) changeOperand(opPos int, operand int) {
	op := code.Opcode(c.currentInstructions()[opPos])
	newInstruction := code.MakeInstruction(op, operand)
	c.replaceInstruction(opPos, newInstruction)
}

// replaceInstruction replaces an instruction at (pos)[position:] with the
// provided instruction
func (c *Compiler) replaceInstruction(pos int, newInstruction []byte) {
	ins := c.currentInstructions()
	for i := 0; i < len(newInstruction); i++ {
		ins[pos+i] = newInstruction[i]
	}
}

// does what it says.
func (c *Compiler) replaceLastPopWithReturn() {
	lastPos := c.scopes[c.scopeIndex].lastInstruction.Position
	ins := code.MakeInstruction(code.OpReturnValue)
	c.replaceInstruction(lastPos, ins)
	c.scopes[c.scopeIndex].lastInstruction.OpCode = code.OpReturnValue
}

// handleJump handles jump operations over conditionals depending on resulting
// truthy value or lack thereof.
func (c *Compiler) handleJump(node *ast.IfExpression, posJumpNotTruthy int) error {
	posJump := c.emit(code.OpJump, 1000)

	posAfterConsequence := len(c.currentInstructions())
	c.changeOperand(posJumpNotTruthy, posAfterConsequence)

	if node.Alternative == nil {
		c.emit(code.OpNull)
	} else {
		err := c.Compile(node.Alternative)
		if err != nil {
			return err
		}
		if c.lastInstructionIs(code.OpPop) {
			c.removeLastPop()
		}
	}
	posAfterAlternative := len(c.currentInstructions())
	c.changeOperand(posJump, posAfterAlternative)
	return nil
}

// addConstant appends ob to the compiler's constant slice.
//
// Returns the index of the constant in the constant pool as its very own identifier
func (c *Compiler) addConstant(ob object.Object) int {
	c.constants = append(c.constants, ob)
	return len(c.constants) - 1
}

// emit generates an instruction and adds it to a collection in memory.
//
// Returns the starting position of the just emitted(added to memory) instruction.
func (c *Compiler) emit(op code.Opcode, operands ...int) int {
	ins := code.MakeInstruction(op, operands...)
	pos := c.addInstruction(ins)
	c.setLastInstruction(op, pos)
	return pos
}

// sets the given opCode as the lastInstruction and shifts the last
// last-instruction to prevInstruction.
func (c *Compiler) setLastInstruction(op code.Opcode, pos int) {
	var (
		prev = c.scopes[c.scopeIndex].lastInstruction
		last = EmittedInstruction{OpCode: op, Position: pos}
	)
	c.scopes[c.scopeIndex].prevInstruction = prev
	c.scopes[c.scopeIndex].lastInstruction = last
}

// addInstruction adds the given (ins) instruction and stores the len of
// already present instruction and returns the same as that will be the
// instruction's offset
func (c *Compiler) addInstruction(ins []byte) int {
	var (
		posOfNewIns = len(c.currentInstructions())
		updatedIns  = append(c.currentInstructions(), ins...)
	)
	c.scopes[c.scopeIndex].instructions = updatedIns
	return posOfNewIns
}

// is pop?
func (c *Compiler) lastInstructionIs(op code.Opcode) bool {
	if len(c.currentInstructions()) == 0 {
		return false
	}
	return c.scopes[c.scopeIndex].lastInstruction.OpCode == op
}

// removeLastPop removes the last instruction from the instructions slice
// and updates the lastInstruction field
func (c *Compiler) removeLastPop() {
	var (
		last = c.scopes[c.scopeIndex].lastInstruction
		prev = c.scopes[c.scopeIndex].prevInstruction

		old  = c.currentInstructions()
		curr = old[:last.Position]
	)
	c.scopes[c.scopeIndex].instructions = curr
	c.scopes[c.scopeIndex].lastInstruction = prev
}

// compileInfix performs the same recursive compilation that Compile does.
func (c *Compiler) compileInfix(node *ast.InfixExpression) error {
	switch {
	case node.Operator == "<":
		err := c.Compile(node.Right)
		if err != nil {
			return err
		}
		err = c.Compile(node.Left)
		if err != nil {
			return err
		}
		c.emit(code.OpGreaterThan)
		return nil
	default:
		err := c.Compile(node.Left)
		if err != nil {
			return err
		}
		err = c.Compile(node.Right)
		if err != nil {
			return err
		}
		err = c.emitInfixOp(node)
		if err != nil {
			return err
		}
	}
	return nil
}

// emitInfixOp emits the corresponding code.Opcode for each infix operator
func (c *Compiler) emitInfixOp(infixExpr *ast.InfixExpression) error {
	switch infixExpr.Operator {
	case "+":
		c.emit(code.OpAdd)
	case "-":
		c.emit(code.OpSub)
	case "*":
		c.emit(code.OpMul)
	case "/":
		c.emit(code.OpDiv)
	case "!=":
		c.emit(code.OpNotEqual)
	case "==":
		c.emit(code.OpEqual)
	case ">":
		c.emit(code.OpGreaterThan)
	default:
		return fmt.Errorf("unknown operator %s", infixExpr.Operator)
	}
	return nil
}

// ByteCode represents the final compiled output of the compiler, containing
// both the executable bytecode instructions and the constant pool. This structure
// is passed to the virtual machine for execution.
//
// Instructions holds the sequential bytecode operations to be executed.
// Constants holds the constant values (integers, strings, etc.) referenced by
// OpConstant instructions via their index in this slice.
type ByteCode struct {
	Instructions code.Instructions
	Constants    []object.Object
}

// ByteCode returns a pointer to ByteCode struct.
func (c *Compiler) ByteCode() *ByteCode {
	return &ByteCode{
		Instructions: c.currentInstructions(),
		Constants:    c.constants,
	}
}
